library(data.tree)
ti <- Node$new("Topic indicators")
    do <- ti$AddChild("dobj")
        va <- do$AddChild("Verb=hankkia/etsiä/etc")
            fp <- va$AddChild("First person")
                fp$AddChild("Asumisen järjestin itselleni jo Suomesta käsin. ")
                fp$AddChild("Asunnon hankin yksityiseltä vuokranantajalta, ja se oli valmiina saapuessani. ")
            va$AddChild("third person / passive")
        do$AddChild("other")
    do <- ti$AddChild("nmod")
        fp <- do$AddChild("First person")
            fp$AddChild("Kuljin rautatieasemalta metrolla yliopiston asuntolalle, missä... ")
        ot <- do$AddChild("Other")
        lc <- ot$AddChild("Locative cases")
            ela <- lc$AddChild("Elative")
                ela$AddChild("Asunnosta muodostui kriittisin osa koko vaihtoa. ")
            ila <- lc$AddChild("Illative")
                ila$AddChild("Suurin osa Pietarin vaihtareista majoittuu samaan asuntolaan, ")
            ine <- lc$AddChild("Inessive")
                ine$AddChild("Meidän lisäksi samassa asunnossa asui italialainen tyttö, jonka kanssa jaoimme vessan, suihkun ja jääkaapin. ")
        ot <- do$AddChild("Asunnon suhteen / kanssa")
            ot$AddChild("Minulla kävi tuuri asunnon kanssa, sillä eräs tuttuni omistaa asunnon Berliinissä. ")
    do <- ti$AddChild("root_")
    do <- ti$AddChild("nsubj")
    do <- ti$AddChild("nmod_gobj")


